### ISSUE TITLE
Expose the chart files in the repository

### ISSUE THREAD

**Issue by samip5** [danopia/helm-land#2]
I want to actually see the Chart.yaml etc files which is currently rather troublesome with this approach.

The main thing I need/other people probably need is to see the values.yaml and chart version.

**Comment by danopia** [comment]
I believe ArtifactHub covers this. Check out [the dns-sync page on Artifact Hub](https://artifacthub.io/packages/helm/cloudydeno/dns-sync), there are sidebar buttons for viewing the default values.yaml as well as the individual template files. The 'Install' button renders a `helm install` command with the latest version, and there's also version history in the sidebar.

The source files are still [in kubernetes-dns-sync's helm-chart folder](https://github.com/cloudydeno/kubernetes-dns-sync/tree/main/helm-chart).

You could also use a local `helm` program e.g. `helm show values cloudydeno/dns-sync` to get the default values, once the repo is added.

I hope ArtifactHub satisfies your needs, if not, I'd like to hear more about what you are expecting from a standard helm repo.

**Comment by samip5** [comment]
> I hope ArtifactHub satisfies your needs, if not, I'd like to hear more about what you are expecting from a standard helm repo.

I expected to find chart files inside a helm repo, aka this repository like you could see [here](https://github.com/k8s-at-home/charts/tree/master/charts) for example. This is what I expected or something like it.

There's no README in ArtifactHub to specify how to use it, and I were mostly searching for the proper things to set into the values. It also doesn't seem to support config from a already existing configmap? Just the config portion would be enough.

Traefik does it like this: https://github.com/traefik/traefik-helm-chart/tree/master/traefik

**Comment by danopia** [comment]
My actual chart source is still in the original repo here: https://github.com/cloudydeno/kubernetes-dns-sync/tree/main/helm-chart

The whole dns-sync project definitely under-documented. If you like writing then maybe you could contribute on the wiki? I'm in the middle of a rewrite of the inner code to be less like external-dns, so better documentation from my side will wait a bit longer.

I definitely don't support using an outside configmap right now, maybe you could PR something that makes your usage easier? I'm not really a helm user to understand how an external configmap would be used.

**Comment by danopia** [comment]
I believe this question is answered by the above links - the helm chart sources live elsewhere, this is just a registry. Closing.
